# Generated by Django 5.0.2 on 2024-02-21 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcases',
            name='problem_statement',
        ),
        migrations.RemoveField(
            model_name='codeformater',
            name='input_for_code',
        ),
        migrations.RemoveField(
            model_name='codeformater',
            name='output_for_code',
        ),
        migrations.AddField(
            model_name='testcases',
            name='code_formater',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.codeformater'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CodeExecuter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_for_code', models.TextField()),
                ('output_for_code', models.TextField()),
                ('code_formater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.codeformater')),
            ],
        ),
        migrations.DeleteModel(
            name='ProblemStatement',
        ),
    ]
